#!/bin/sh
# $OpenBSD: Xsetup_0.in,v 1.1 2021/08/30 15:38:27 matthieu Exp $

prefix="/usr/X11R6"
exec_prefix="${prefix}"

xrandr --output default --dpi 96

xset fp+ /usr/local/share/fonts/terminus

XRES=$(xrdb -query)

BG_COLOR=$(echo "$XRES" | awk '/xroot.background/ { print $2 }')
xsetroot -solid $BG_COLOR

for CLK in date time; do
	FACE=$(echo "$XRES" | grep "xclock.${CLK}Face" | xargs | cut -d ' ' -f 2-)
	GEOM=$(echo "$XRES" | grep "xclock.${CLK}Geom" | xargs | cut -d ' ' -f 2-)
	STR=$(echo "$XRES" | grep "xclock.${CLK}Str" | xargs | cut -d ' ' -f 2-)

	xclock -face "$FACE" -geometry "$GEOM" -strftime "$STR" &
done

(
while true; do
	xmessage -geometry +540-32 -buttons "[ Sleep ]":20,"[ Restart ]":21,"[ Shutdown ]":22 ""
	ACTION=$?
	echo "Xmessage said: $ACTION"
	if [ "$ACTION" -eq 20 ]; then
		/usr/sbin/zzz
	elif [ "$ACTION" -eq 21 ]; then
		xsetroot -cursor_name watch
		/sbin/shutdown -r now
	elif [ "$ACTION" -eq 22 ]; then
		xsetroot -cursor_name watch
		/sbin/shutdown -p now
	else
		echo "Unexpected action form Xmessage"
	fi
	if [ -z "$(pgrep -U root xclock)" ]; then
		break
	fi
done
) &

#${exec_prefix}/bin/xsetroot -fg \#6f6f6f -bg \#bfbfbf -bitmap ${prefix}/include/X11/bitmaps/root_weave

#${exec_prefix}/bin/xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail

#  install package openbsd-backgrounds
#  then uncomment:
#
# if test -x /usr/local/bin/openbsd-wallpaper
# then
# 	/usr/local/bin/openbsd-wallpaper
# fi

# sxpm OpenBSD.xpm &
